# March 2018

## 03/10 Sat
Running python hello world. Tried to make kmalloc use buddy directly.

### put_pcache in pcache_zap_pte
So this time, python keep running for a long time. But P crashed when the first time eviction was triggered.

Below is log from S side, those libraries do not exist, so these log are fine:
```
S:
[Mar10 10:39] handle_access_request /etc/ld.so.preload 4, -2
[Mar10 10:44] local_file_open : Cannot open required file [/usr/lib64/python2.7/site.so].
[  +0.352839] local_file_open : Cannot open required file [/usr/lib64/python2.7/sitemodule.so].
[ +22.254465] local_file_open : Cannot open required file [/usr/lib64/python2.7/os.so].
[  +0.350759] local_file_open : Cannot open required file [/usr/lib64/python2.7/osmodule.so].
[Mar10 10:45] local_file_open : Cannot open required file [/usr/lib64/python2.7/posixpath.so].
[  +0.358045] local_file_open : Cannot open required file [/usr/lib64/python2.7/posixpathmodule.so].
[ +13.421033] local_file_open : Cannot open required file [/usr/lib64/python2.7/stat.so].
[  +0.352838] local_file_open : Cannot open required file [/usr/lib64/python2.7/statmodule.so].
[Mar10 10:46] local_file_open : Cannot open required file [/usr/lib64/python2.7/genericpath.so].
[  +0.360126] local_file_open : Cannot open required file [/usr/lib64/python2.7/genericpathmodule.so].
[ +11.582165] local_file_open : Cannot open required file [/usr/lib64/python2.7/warnings.so].
[  +0.357003] local_file_open : Cannot open required file [/usr/lib64/python2.7/warningsmodule.so].
[ +11.989828] local_file_open : Cannot open required file [/usr/lib64/python2.7/linecache.so].
[  +0.358043] local_file_open : Cannot open required file [/usr/lib64/python2.7/linecachemodule.so].
[Mar10 10:47] local_file_open : Cannot open required file [/usr/lib64/python2.7/types.so].
[  +0.353879] local_file_open : Cannot open required file [/usr/lib64/python2.7/typesmodule.so].
```

Weird P's bug, seems like the pcm returned by evict_find_line has issue. Well, I'm trying to debug what is going with this set.
```c hl_lines="29 30"
wuklab13 0310-2
[ 1046.880649] SYSC_read() cpu(5) tsk(32/32/python) user-ip:0x7ffff6e117e0
[ 1046.959692]     fd: 8, buf: 00007ffff7ffb000, count: 4096
[ 1048.726624] pcache_evict_line(): pset: ffff88207f9ffec0, for uva: 0x7ffff7ffb000
[ 1048.813053] ------------[ cut here ]------------
[ 1048.868174] BUG: failure at ./include/processor/pcache.h:284/pcache_meta_to_pcache_set()!
[ 1048.965937] Kernel Panic - not syncing: BUG!
[ 1049.016898] CPU: 5 PID: 32 Comm: python 4.0.0-lego-ys+ #347
[ 1049.083460] Stack:
[ 1049.107380] ffff88107e18fca8 ffffffff81026f1c 0000000000000008 ffff88107e18fcb8
[ 1049.194743] ffff88107e18fc70 0000000021475542 0000000000000000 0000000000000000
[ 1049.282107] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[ 1049.369468] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[ 1049.456832] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[ 1049.544193] Call Trace:
[ 1049.573315] <TSK>
[ 1049.596195] [<ffffffff81026f28>] panic+0xc2/0xeb
[ 1049.651318] [<ffffffff8101c3fc>] ? task_tick_rt+0x2c/0xd0
[ 1049.715799] [<ffffffff81019a65>] ? scheduler_tick+0x55/0x60
[ 1049.782360] [<ffffffff81017035>] ? tick_handle_periodic+0x45/0x70
[ 1049.855163] [<ffffffff81006764>] ? apic_timer_interrupt+0x54/0x90
[ 1049.927966] [<ffffffff8101c3fc>] ? task_tick_rt+0x2c/0xd0
[ 1049.992447] [<ffffffff81019a65>] ? scheduler_tick+0x55/0x60
[ 1050.059009] [<ffffffff81017035>] ? tick_handle_periodic+0x45/0x70
[ 1050.131812] [<ffffffff8103c41a>] ? put_dec+0x1a/0x80
[ 1050.191093] [<ffffffff81006764>] ? apic_timer_interrupt+0x54/0x90
[ 1050.263895] [<ffffffff8100e56a>] ? smp__apic_timer_interrupt+0x6a/0x70
[ 1050.341897] [<ffffffff81012ded>] ? printk+0x11d/0x1b0
[ 1050.402219] [<ffffffff810340c5>] dump_pcache_meta+0xc5/0xd0
[ 1050.468782] [<ffffffff81034588>] pcache_evict_line+0x158/0x220
[ 1050.538463] [<ffffffff81030f5e>] pcache_alloc+0x22e/0x2f0
[ 1050.602945] [<ffffffff8103015a>] common_do_fill_page+0x2a/0x430
[ 1050.673668] [<ffffffff8102fb20>] ? pcache_meta_to_kva+0x30/0x30
[ 1050.744389] [<ffffffff81030702>] pcache_handle_fault+0x1a2/0x6c0
[ 1050.816152] [<ffffffff810103d2>] do_page_fault+0xa2/0x1a0
[ 1050.880634] [<ffffffff8100db9f>] page_fault+0x1f/0x30
[ 1050.940955] [<ffffffff8103bb82>] ? copy_user_enhanced_fast_string+0x2/0x10
[ 1051.023118] [<ffffffff81038423>] ? normal_p2m_read+0x233/0x330
[ 1051.092800] [<ffffffff810363ce>] sys_read+0x9e/0x160
[ 1051.152081] [<ffffffff810268d0>] ? strace_enter_default+0x30/0x40
[ 1051.224884] [<ffffffff8100e935>] do_syscall_64+0x45/0xd0
[ 1051.288326] [<ffffffff8100d82c>] entry_SYSCALL64_slow_path+0x25/0x25
```

Interesting, added several debug messages. The bug is I forgot to put_pcache when a rmap was zapped. One rmap counts one refcount (effectively one process), thus when a rmap was zapped, we should decrease the refcount. I found I've already done so for `pcache_remove_rmap`, and `pcache_move_pte`. But damn, forgot this one. I remember this code was written before fork+pcache. So.. I don't have a big picture at that time. __Multithreaded system plus background reclaim really a very rigours design usage of refcount and lock__.
```
[ 1418.038411] CPU5 PID32 sys_read+0x0/0xa0
[ 1418.085227] pcache_evict_line(): pset: ffff88207f9ffec0, for uva: 0x7ffff7ffb000
[ 1418.173617] pset:ffff88207f9ffec0 set_idx: 32763 nr_lru:8
[ 1418.238105] pcache:ffff8801801ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880107ffb000
[ 1418.351476] pcache:ffff8801805ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880117ffb000
[ 1418.464847] pcache:ffff8801809ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880127ffb000
[ 1418.578220] pcache:ffff880180dffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880137ffb000
[ 1418.691591] pcache:ffff8801811ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880147ffb000
[ 1418.804963] pcache:ffff8801815ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880157ffb000
[ 1418.918334] pcache:ffff8801819ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880167ffb000
[ 1419.031706] pcache:ffff880181dffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880177ffb000
[ 1419.145077] After dump pset
[ 1419.176280] pcache:ffff8801801ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880107ffb000
[ 1419.289652] pcache dumped because: evict_find_line_lru
[ 1419.351018] pcache:ffff8801805ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880117ffb000
[ 1419.464389] pcache dumped because: evict_find_line_lru
[ 1419.525757] pcache:ffff8801809ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880127ffb000
[ 1419.639127] pcache dumped because: evict_find_line_lru
[ 1419.700494] pcache:ffff880180dffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880137ffb000
[ 1419.813865] pcache dumped because: evict_find_line_lru
[ 1419.875231] pcache:ffff8801811ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880147ffb000
[ 1419.988604] pcache dumped because: evict_find_line_lru
[ 1420.049969] pcache:ffff8801815ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880157ffb000
[ 1420.163341] pcache dumped because: evict_find_line_lru
[ 1420.224708] pcache:ffff8801819ffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880167ffb000
[ 1420.338079] pcache dumped because: evict_find_line_lru
[ 1420.399445] pcache:ffff880181dffec0 mapcount:0 refcount:1 flags:(allocated|usable) kva: ffff880177ffb000
[ 1420.512817] pcache dumped because: evict_find_line_lru
[ 1420.574183] evict_find_line_lru(): pcm: ffff88207f9ffea8
[ 1420.637631] ------------[ cut here ]------------
[ 1420.692756] BUG: failure at ./include/processor/pcache.h:340/pcache_meta_to_kva()!
[ 1420.783245] Kernel Panic - not syncing: BUG!
[ 1420.834210] CPU: 5 PID: 32 Comm: python 4.0.0-lego-ys+ #349
[ 1420.900777] Stack:
```

### python hello world run to end
Glad to say, python hello world finished, even with some missed syscalls. Especially the stdin stuff, so the string is actually not printed out. Log is wuklab13:~/ys/0310-4
```c hl_lines="52 14 15"
[ 3149.540308] CPU5 PID32 sys_ioctl+0x0/0x10
[ 3149.588144] CPU5 PID32 sys_ioctl+0x0/0x10
[ 3149.635982] CPU5 PID32 sys_write+0x0/0xa0
[ 3149.683818] STDOUT: ---[
>>>
]---
[ 3149.726456] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff6d9aeb0 flags:0x150
[ 3149.926247] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff6d9aeb0 flags:0x150 ret:0(OKAY)
[ 3150.033464] CPU5 PID32 sys_newfstat+0x0/0x10
[ 3150.084420] CPU5 PID32 sys_ioctl+0x0/0x10
[ 3150.132256] strace__mmap cpu5 addr=0x0, len=0x1000, prot(0x3)=PROT_READ|PROT_WRITE, flags(0x22)=MAP_PRIVATE|MAP_ANONYMOUS, fd=18446744073709551615( ), off=0x0
[ 3150.301772] CPU5 PID32 sys_read+0x0/0xa0
[ 3150.348562] ------------[ cut here ]------------
[ 3150.403679] WARNING: CPU: 5 PID: 32 at managers/processor/fs/stdio.c:24 stdio_file_read+0x30/0x50
[ 3150.509751] Process wants STDIN!
[ 3150.546149] CPU: 5 PID: 32 Comm: python 4.0.0-lego-ys+ #352
[ 3150.612705] Stack:
[ 3150.636624] ffff88107e18fe90 ffffffff81012b15 ffffffff811464e0 00007ffff7ffb000
[ 3150.723977] 0000000000000400 00007ffff70e5640 ffff88107e18fef0 ffffffff81012bd2
[ 3150.811331] ffffffff81079d6b ffff881000000018 ffff88107e18ff00 ffff88107e18fec0
[ 3150.898687] 0000000000000020 ffffffff810346b0 0000000000000022 ffffffff811464f0
[ 3150.986040] 00007ffff7fdf740 0000000000000000 ffff88107e18ff00 ffffffff81035ac0
[ 3151.073394] Call Trace:
[ 3151.102514] <TSK>
[ 3151.125392] [<ffffffff81012b21>] __warn.constprop.0+0x91/0xd0
[ 3151.194028] [<ffffffff81012bd2>] warn_slowpath_fmt+0x42/0x50
[ 3151.261623] [<ffffffff810346b0>] ? sweep_pset_lru+0x220/0x220
[ 3151.330259] [<ffffffff81035ac0>] stdio_file_read+0x30/0x50
[ 3151.395775] [<ffffffff810346e3>] sys_read+0x33/0xa0
[ 3151.454010] [<ffffffff8100e875>] do_syscall_64+0x45/0xd0
[ 3151.517446] [<ffffffff8100d76c>] entry_SYSCALL64_slow_path+0x25/0x25
[ 3151.593362] <EOT>
[ 3151.616240] ---[ end trace 0000000000000000 ]---
[ 3151.671360] CPU5 PID32 sys_write+0x0/0xa0
[ 3151.719194] STDOUT: ---[


]---
[ 3151.759756] CPU5 PID32 sys_close+0x0/0x140
[ 3151.808628] SYSC_close(): [3] -> [/root/ys/py_hello.py]
[ 3151.871028] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a79380 flags:0x150
[ 3152.070817] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a79380 flags:0x150 ret:0(OKAY)
[ 3152.178033] CPU5 PID32 sys_rt_sigaction+0x0/0xb0
[ 3152.234151] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a77f60 flags:0x150
[ 3152.432941] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a77f60 flags:0x150 ret:0(OKAY)
[ 3152.540242] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff73ee794 flags:0x150
[ 3152.739952] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff73ee794 flags:0x150 ret:0(OKAY)
[ 3152.847171] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff715b278 flags:0x150
[ 3153.046958] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff715b278 flags:0x150 ret:0(OKAY)
[ 3153.154179] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff6de74f0 flags:0x150
[ 3153.353965] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff6de74f0 flags:0x150 ret:0(OKAY)
[ 3153.461180] CPU5 PID32 sys_exit_group+0x0/0x10

```

### Trying phoenix pthread again
4GB pcache, 1GB dataset.

1^th^ run with CONFIG_STRACE on, 1GB dataset finished, result is correct.

2^th^ run without CONFIG_STRACE, 1GB dataset stuck. Two weird things:

- open/close dev/cpu/online file too many times than a normal linux run
- IB stucked
So next I'm going to try add a lock to ibapi, see if it is ib internal deadlock issue.

```c
wuklab13 0310-7
[  702.895936] Processor: Processor manager is running.
[  722.400159] STDOUT: ---[
envp[0] HOME=/

]---
[  722.453307] STDOUT: ---[
envp[1] TERM=linux

]---
[  722.512589] STDOUT: ---[
argv[0] /root/ys/phoenix/phoenix-2.0/tests/word_count/word_count-pthread

]---
[  722.628036] STDOUT: ---[
argv[1] /root/ys/phoenix/phoenix-2.0/tests/word_count/word_count_datafiles/word_1GB.txt

]---
[  722.759101] STDOUT: ---[
Wordcount: Running...
]---
[  722.819406] STDOUT: ---[


]---
[  722.860139] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  722.940653] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.011483] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.084287] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.157090] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.229894] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.302698] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.375502] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.448306] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.521111] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.593914] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.666718] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.739522] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.812326] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  723.885130] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  766.701260] ibapi_send_reply() polling timeout (30010 ms), caller: net_send_reply_timeout+0x11b/0x1ee
[  766.809538]  net_send_reply_timeout() caller: __pcache_do_fill_page+0x82/0x140
[  766.895863] word_count-pthr[65]: segfault at 0x7fffb5eba000 ip 000000000040249d sp 00007fffb5e9ad80 error 6
[  767.012348] CPU: 15 PID: 65 Comm: word_count-pthr 4.0.0-lego-ys+ #359
[  767.089312] RIP: 0033:[<000000000040249d>]  [<000000000040249d>] 0x40249d
[  767.170436] RSP: 002b:00007fffb5e9ad80  EFLAGS: 00010216
[  767.233879] RAX: 00007fffb5eba000 RBX: 0000000000001388 RCX: 000000000000004f
[  767.319164] RDX: 00007fffe4ea92a4 RSI: 00007fffe626fac9 RDI: 00007fffe4ea92a4
[  767.404449] RBP: 00000000007540e0 R08: 0000000000000000 R09: 0000000000014fa0
[  767.489733] R10: 0000000000427fb0 R11: 0000000000000202 R12: 0000000000012b12
[  767.575018] R13: 00007fff496ab890 R14: 00007fff48704fb0 R15: 0000000000001388
[  767.660303] FS:  00007fffb5e9b700(0000) GS:ffff88207fce0000(0000) knlGS:0000000000000000
[  767.757028] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  767.825671] CR2: 00007fffb5eba000 CR3: 000000207fe3a000 CR4: 00000000000406a0
[  767.910958] get_signal(): dequeue_signr: 11, handler:          (null)
[  767.987928] get_signal(): dequeue_signr: 9, handler:          (null)
```

3^th^ run, without STRACE, with locked ibapi, it finished, result is correct. Runtime: `18.692936 sec`.
```c
[  555.423623] nr_pgfault: 288100
[  555.458042] nr_pgfault_wp: 0
[  555.492360] nr_pgfault_wp_cow: 0
[  555.530838] nr_pgfault_wp_reuse: 0
[  555.571396] nr_pgfault_due_to_concurrent_eviction: 0
[  555.630673] nr_pcache_fill_from_memory: 288081
[  555.683710] nr_pcache_fill_from_victim: 12
[  555.732588] nr_pcache_eviction: 494
[  555.774187] nr_victim_eviction: 474
```

4th run, same setting with the 3^th^ run, same result. But the nr_pgfault differs, I guess it is due to runtime things. Runtime: `19.12861 sec`.
```c
[  469.891700] nr_pgfault: 288119
[  469.926123] nr_pgfault_wp: 0
[  469.960444] nr_pgfault_wp_cow: 0
[  469.998924] nr_pgfault_wp_reuse: 0
[  470.039484] nr_pgfault_due_to_concurrent_eviction: 0
[  470.098764] nr_pcache_fill_from_memory: 288093
[  470.151805] nr_pcache_fill_from_victim: 12
[  470.200684] nr_pcache_eviction: 513
[  470.242285] nr_victim_eviction: 493
```

5th run, same with 4th, succeed, Runtime: `18.653879 sec`.
```
[  313.202348] nr_pgfault: 288070
[  313.236772] nr_pgfault_wp: 0
[  313.271093] nr_pgfault_wp_cow: 0
[  313.309575] nr_pgfault_wp_reuse: 0
[  313.350139] nr_pgfault_due_to_concurrent_eviction: 0
[  313.409421] nr_pcache_fill_from_memory: 288052
[  313.462465] nr_pcache_fill_from_victim: 6
[  313.510307] nr_pcache_eviction: 446
[  313.551909] nr_victim_eviction: 432
```

6th, setting is the same, but with 4GB dataset, crashed:
```c
[  512.028141] Processor: Processor manager is running.
[  529.375605] STDOUT: ---[
Wordcount: Running...
]---
[  529.435906] STDOUT: ---[


]---
[  529.476660] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[  529.555983] ------------[ cut here ]------------
[  529.609128] BUG: failure at managers/processor/pcache/rmap.c:735/pcache_zap_pte()!
[  529.699613] Kernel Panic - not syncing: BUG!
[  529.750576] CPU: 5 PID: 32 Comm: word_count-pthr 4.0.0-lego-ys+ #361
[  529.826500] Stack:
[  529.850422] ffff88107e1a3dd8 ffffffff810259b4 0000000000000008 ffff88107e1a3de8
[  529.937787] ffff88107e1a3da0 0000000021475542 0000000000000000 0000000000000000
[  530.025152] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  530.112517] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  530.199882] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  530.287247] Call Trace:
[  530.316370] <TSK>
[  530.339251] [<ffffffff810259c0>] panic+0xc2/0xeb
[  530.394374] [<ffffffff8106190a>] ? client_internal_poll_sendcq+0x2a/0x80
[  530.474458] [<ffffffff8101bfcc>] ? task_tick_rt+0x2c/0xd0
[  530.538943] [<ffffffff81019725>] ? scheduler_tick+0x55/0x60
[  530.605506] [<ffffffff81016df5>] ? tick_handle_periodic+0x45/0x70
[  530.678311] [<ffffffff8103768a>] ? put_dec+0x1a/0x80
[  530.737595] [<ffffffff810066f4>] ? apic_timer_interrupt+0x54/0x90
[  530.810398] [<ffffffff8100e4aa>] ? smp__apic_timer_interrupt+0x6a/0x70
[  530.888403] [<ffffffff81012ccd>] ? printk+0x11d/0x1b0
[  530.948726] [<ffffffff81030429>] pcache_zap_pte+0xf9/0x160
[  531.014250] [<ffffffff8102f090>] ? __pcache_move_pte_fastpath+0x50/0x50
[  531.093295] [<ffffffff8102c8dc>] unmap_page_range+0x32c/0x3b0
[  531.161940] [<ffffffff8102c97e>] release_pgtable+0x1e/0x40
[  531.227463] [<ffffffff8102bfb3>] sys_munmap+0xc3/0x120
[  531.288827] [<ffffffff8100e86d>] do_syscall_64+0x3d/0xc0
[  531.352270] [<ffffffff8100d76c>] entry_SYSCALL64_slow_path+0x25/0x25
```

7th run, add debug info, does not seem that useful:
```c
]---
[15755.579501] SYSC_close(): [4] -> [/sys/devices/system/cpu/online]
[15755.672760] pte:ffff88107e1a3dd8 pfn:0x8207e80b flags:(dirty|large|global|softw4|pkey0|pkey1|pkey2|pkey3|nx|0x3ff800000000000)
[15755.807015] pte dumped because: Invalid pte
[15755.856932] address: 0x7ffefc638000
[15755.899569] ------------[ cut here ]------------
[15755.954684] BUG: failure at managers/processor/pcache/rmap.c:747/pcache_zap_pte()!
[15756.045159] Kernel Panic - not syncing: BUG!
[15756.096114] CPU: 5 PID: 32 Comm: word_count-pt
```

Tried several times, even with mmap/munmap debug option on, it crashed at the same point. Key is address `0x7ffefc638000`, and the mmap() related to it.

Close to find the bug. Latest log in 0310-18.

---
## 03/09 Fri

### Find bug in kmalloc

Tried to print pud in every syscall and catch the criminal:
```c hl_lines="2 7 25 29"
wuklab13 0309-1
[  320.088684] CPU5 PID32 sys_close+0x0/0x1f0
[  320.137567] do_syscall_64(): enter pgd ffff88207fccf000, pgd.cont_va ffff88207fc6f000, pud_index=0x0 pud: ffff88207fc6f000
[  320.269657] SYSC_close() cpu(5) tsk(32/32/python) user-ip:0x7ffff7df3c37
[  320.349742]     3
[  320.372624] SYSC_close(): [3] -> [/lib64/libpython2.7.so.1.0]
[  320.441268] SYSC_close() cpu(5) tsk(32/32/python) ret: 0x0 (0)
[  320.510954] do_syscall_64(): leave pgd ffff88207fccf000, pgd.cont_va ffff88207fc6f000, pud_index=0x0 pud: ffff88207fc6f000

[  320.643043]     addr: 0x7ffff7a101f0, pgd: ffff88207fccf7f8
[  320.709607]     addr: 0x7ffff7a101f0, pgd: ffff88207fccf7f8 pud ffff88207fcaeff8
[  320.798014] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a101f0 flags:0x50
[  320.995755] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a101f0 flags:0x50 ret:0(OKAY)

[  321.101944]     addr: 0x7ffff7a21749, pgd: ffff88207fccf7f8
[  321.168509]     addr: 0x7ffff7a21749, pgd: ffff88207fccf7f8 pud ffff88207fcaeff8
[  321.256914] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a21749 flags:0x50
[  321.454651] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a21749 flags:0x50 ret:0(OKAY)

[  321.560845]     addr: 0x7ffff7ff2fda, pgd: ffff88207fccf7f8
[  321.627409]     addr: 0x7ffff7ff2fda, pgd: ffff88207fccf7f8 pud ffff88207fcaeff8
[  321.715815] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7ff2fda flags:0x50
[  321.913553] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7ff2fda flags:0x50 ret:0(OKAY)

[  322.019745] CPU5 PID32 sys_open+0x0/0x10
[  322.066548] do_syscall_64(): enter pgd ffff88207fccf000, pgd.cont_va ffff9001801ff000, pud_index=0x0 pud: ffff9001801ff000
[  322.198638] SYSC_open() cpu(5) tsk(32/32/python) user-ip:0x7ffff7df3b27
[  322.277683]     f_name: /lib64/libpthread.so.0, flags: 80000, mode: e150
[  322.357780] SYSC_open() cpu(5) tsk(32/32/python) ret: 0x3 (3)
[  322.426414] do_syscall_64(): leave pgd ffff88207fccf000, pgd.cont_va ffff9001801ff000, pud_index=0x0 pud: ffff9001801ff000
```

After printing more in pcache_handle_fault, I found who corrupted pgtable:
```c hl_lines="23 28"
wuklab13 0309-5
[  661.308584] CPU5 PID32 sys_close+0x0/0x1f0
[  661.357466] do_syscall_64(): enter pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  661.489557] SYSC_close() cpu(5) tsk(32/32/python) user-ip:0x7ffff7df3c37
[  661.569642]     3    
[  661.592525] SYSC_close(): [3] -> [/lib64/libpython2.7.so.1.0]
[  661.661170] SYSC_close() cpu(5) tsk(32/32/python) ret: 0x0 (0)
[  661.730854] do_syscall_64(): leave pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  661.862944] pcache_handle_fault(): enter pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  662.001275]     addr: 0x7ffff7a101f0, pgd: ffff88207fccf7f8
[  662.067840]     addr: 0x7ffff7a101f0, pgd: ffff88207fccf7f8 pud ffff88207fcafff8
[  662.156247] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a101f0 flags:0x50
[  662.353985] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a101f0 flags:0x50 ret:0(OKAY)
[  662.460176] pcache_handle_fault(): leave pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000

[  662.600586] pcache_handle_fault(): enter pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  662.738916]     addr: 0x7ffff7a21749, pgd: ffff88207fccf7f8
[  662.805481]     addr: 0x7ffff7a21749, pgd: ffff88207fccf7f8 pud ffff88207fcafff8
[  662.893888] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a21749 flags:0x50
[  663.091636] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a21749 flags:0x50 ret:0(OKAY)
[  663.197831] pcache_handle_fault(): leave pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000

[  663.338242] pcache_handle_fault(): enter pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  663.476572]     addr: 0x7ffff7ff2fda, pgd: ffff88207fccf7f8
[  663.543135]     addr: 0x7ffff7ff2fda, pgd: ffff88207fccf7f8 pud ffff88207fcafff8
[  663.631543] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7ff2fda flags:0x50
[  663.829279] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7ff2fda flags:0x50 ret:0(OKAY)
[  663.935472] pcache_handle_fault(): leave pgd ffff88207fccf000, pgd.cont_va ffff9001801ff000, pud_index=0x0 pud: ffff9001801ff000

[  664.075884] CPU5 PID32 sys_open+0x0/0x10
[  664.122686] do_syscall_64(): enter pgd ffff88207fccf000, pgd.cont_va ffff9001801ff000, pud_index=0x0 pud: ffff9001801ff000
[  664.254776] SYSC_open() cpu(5) tsk(32/32/python) user-ip:0x7ffff7df3b27
[  664.333821]     f_name: /lib64/libpthread.so.0, flags: 80000, mode: e150
[  664.413918] SYSC_open() cpu(5) tsk(32/32/python) ret: 0x3 (3)
[  664.482552] do_syscall_64(): leave pgd ffff88207fccf000, pgd.cont_va ffff9001801ff000, pud_index=0x0 pud: ffff9001801ff000
```

Then, try catching bug with address `0x7ffff7ff2fda` fault. Printing still being the most effective way to debug. :-)

Dig further, I found pgtable corrupted after `pcache_add_rmap()`, namely after `alloc_pcache_rmap()`:
```c
[ 5024.482570] pcache_add_rmap() 343 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[ 5024.613601] alloc_pcache_rmap(): size: 56, rmap: ffff88207fccefd0
[ 5024.686396] pcache_add_rmap() 358 pgd ffff88207fccf000, pgd.cont_va ffff90207fcce000, pud_index=0x0 pud: ffff90207fcce000
```

Well, `rmap: ffff88207fccefd0` & `ffff90207fcce000`, clearly
```c hl_lines="4 5 6 34 48"
[  843.916517] pcache_add_rmap() 372 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  844.047557] alloc_pcache_rmap() 60 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  844.179638] alloc_pcache_rmap(): size: 56, rmap: ffff88207fccefd0
[  844.252438] alloc_pcache_rmap() 71 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  844.384517] alloc_pcache_rmap(): size: 56, rmap: ffff88207fccefd0
[  844.457317] alloc_pcache_rmap() 85 pgd ffff88207fccf000, pgd.cont_va ffff90207fcce000, pud_index=0x0 pud: ffff90207fcce000
[  844.589398] pcache_add_rmap() 387 pgd ffff88207fccf000, pgd.cont_va ffff90207fcce000, pud_index=0x0 pud: ffff90207fcce000

46 static struct pcache_rmap *alloc_pcache_rmap(void)
47 {
48         struct pcache_rmap *rmap;
49
50         pgd_t *pgd;
51         pud_t *pud;
52         unsigned long addr;
53         struct mm_struct *mm = current->mm;
54
55         if (pall) {
56                 addr = 0x601008;
57                 pgd = pgd_offset(mm, addr);
58                 pud = pud_alloc(mm, pgd, addr);
59                 pr_info("%s() %d pgd %p, pgd.cont_va %lx, pud_index=%#lx pud: %p\n",
60                         __func__, __LINE__, pgd, pgd_page_vaddr(*pgd), pud_index(addr), (void *)pud);
61         }
62
63         rmap = kmalloc(sizeof(*rmap), GFP_KERNEL);
64
65         if (pall) {
66                 addr = 0x601008;
67                 pgd = pgd_offset(mm, addr);
68                 pud = pud_alloc(mm, pgd, addr);
69                 pr_info("%s(): size: %zu, rmap: %p\n", __func__, sizeof(*rmap), rmap);
70                 pr_info("%s() %d pgd %p, pgd.cont_va %lx, pud_index=%#lx pud: %p\n",
71                         __func__, __LINE__, pgd, pgd_page_vaddr(*pgd), pud_index(addr), (void *)pud);
72         }
73
74         if (rmap) {
75                 INIT_LIST_HEAD(&rmap->next);
76                 rmap->flags = 0;
77         }
78
79         if (pall) {
80                 addr = 0x601008;
81                 pgd = pgd_offset(mm, addr);
82                 pud = pud_alloc(mm, pgd, addr);
83                 pr_info("%s(): size: %zu, rmap: %p\n", __func__, sizeof(*rmap), rmap);
84                 pr_info("%s() %d pgd %p, pgd.cont_va %lx, pud_index=%#lx pud: %p\n",
85                         __func__, __LINE__, pgd, pgd_page_vaddr(*pgd), pud_index(addr), (void *)pud);
86         }
87
88         return rmap;
89 }

```

Narrow it down to `INIT_LIST_HEAD`:
```c hl_lines="3 4 11"
[ 1334.548682] alloc_pcache_rmap(): size: 56, rmap: ffff88207fccefd0
[ 1334.621487] alloc_pcache_rmap() 71 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[ 1334.753576] alloc_pcache_rmap() 76 &rmap->next ffff88207fcceff8 &flags ffff88207fccefd8
[ 1334.922067] alloc_pcache_rmap() 86 pgd ffff88207fccf000, pgd.cont_va ffff90207fcce000, pud_index=0x0 pud: ffff90207fcce000
[ 1335.126962] alloc_pcache_rmap() 98 pgd ffff88207fccf000, pgd.cont_va ffff90207fcce000, pud_index=0x0 pud: ffff90207fcce000

74         if (rmap) {
75         pr_info("%s() %d &rmap->next %p &flags %p\n",
76                 __func__, __LINE__, &rmap->next, &rmap->flags);
77
78                 INIT_LIST_HEAD(&rmap->next);
79
80         if (pall) {
81                 addr = 0x601008;
82                 pgd = pgd_offset(mm, addr);
83                 pud = pud_alloc(mm, pgd, addr);
84                 pr_info("%s(): size: %zu, rmap: %p\n", __func__, sizeof(*rmap), rmap);
85                 pr_info("%s() %d pgd %p, pgd.cont_va %lx, pud_index=%#lx pud: %p\n",
86                         __func__, __LINE__, pgd, pgd_page_vaddr(*pgd), pud_index(addr), (void *)pud);
87         }
88
89                 rmap->flags = 0;
90         }
```

Seriously, if this is running on user-level on VM, I would be able to find the bug maybe in 30min. But I spent several hours to find it out with physical machine. Damn you physical machine.

Hmm, this func is used A LOT. How can it fail at this point? Possible reasons:

- kmalloced area happen to intersect with pgtable?
- one physical page is mapped twice? one to pgtable, one by this rmap.
- tty/serial code has bug? Really ancient code.

After add a few printk, IB seems stuck. And this happens just with few more lines of code! Why? code size matters?
```c
[  722.381469] pcache_handle_fault(): enter pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[  722.519778]     addr: 0x7ffff7feffcc, pgd: ffff88207fccf7f8
[  722.586334]     addr: 0x7ffff7feffcc, pgd: ffff88207fccf7f8 pud ffff88207fcafff8
[  722.674727] Before fill address=0x7ffff7feffcc set_idx:0x7fef
[  722.743362] pcache:ffff8801801ffbc0 mapcount:0 refcount:1 flags:(allocated|usable) set_idx=0x7fef kva: ffff880107fef000
[  722.872312] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7feffcc flags:0x50
[  722.967985] __pcache_do_fill_page(): before net pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
last line
```

Well, the following finding finally find the bug line. And it kind of explains the above bug. Probably kmalloc'ed area has issues, so IB is touching wrong data. The following bug is related to kmalloc, the rmap is 56 bytes, and it should be within 1 single page, but it is not:
```c hl_lines="3 4 8 9 10"
[ 1862.307427] pcache_add_rmap() 413 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[ 1862.438477] alloc_pcache_rmap() 86 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[ 1862.570568] sp->units: 50 SLOB_UNITS: 32
[ 1862.617372] alloc_pcache_rmap(): size: 56, rmap: ffff88207fccefd0
[ 1862.690178] alloc_pcache_rmap() 97 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[ 1862.822268] alloc_pcache_rmap() 104 &rmap->next ffff88207fcceff8 &flags ffff88207fccefd8
[ 1862.918995] __INIT_LIST_HEAD(): next ffff88207fcceff8 prev ffff88207fccf000
[ 1863.002202] __INIT_LIST_HEAD() 63 pgd ffff88207fccf000, pgd.cont_va ffff88207fcae000, pud_index=0x0 pud: ffff88207fcae000
[ 1863.133253] __INIT_LIST_HEAD(): next ffff88207fcceff8 prev ffff88207fccf000
[ 1863.216459] alloc_pcache_rmap(): size: 56, rmap: ffff88207fccefd0
[ 1863.289265] alloc_pcache_rmap() 114 pgd ffff88207fccf000, pgd.cont_va ffff90207fcce000, pud_index=0x0 pud: ffff90207fcce000
```

Analysis: The @prev field in line 7 has address `ffff88207fccf000`, which happen to the pgd page (`pgd ffff88207fccf000`). Thus when we do `list->prev = list`, it writes to the first 8 bytes of pgd page, corrupts the original pgd entry. That is why we see a corrupted pgd entry (`ffff90207fcce000`).

This roots from kmalloc, which should not allocate such an object that cross two pages.

---
## 03/08 Thur
Took several days off. This morning finished the porting of `wait4` and `waitid`, which actually has a lot code change. The concept and mechanism is fairly simple, but the legacy UNIX tradition make the implementation quite complex.

Now, look back to finish debugging the pcache issue. It must be fixed this week.

### python
Tried `python hello_world.py`, the program runs for a while and crashes at a deterministic point:
```c hl_lines="4 8 39"
wuklab13 and wuklab15, ~/ttyS1
[419097.929969] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a4b008 flags:0x50 ret:0(OKAY)
[419098.039145] __pcache_do_fill_page(): I pid:32 tgid:32 address:0x7ffff7a4c010 flags:0x50
[419098.306537] __pcache_do_fill_page(): O pid:32 tgid:32 address:0x7ffff7a4c010 flags:0x50 ret:0(OKAY)
[419098.413756] CPU5 PID32 sys_mprotect+0x0/0x90
[419098.465753] SYSC_mprotect() cpu(5) tsk(32/32/python) user-ip:0x7ffff7df3d27
[419098.549990]     start:0x7ffff7d8c000,len:0x2000,prot:0x1
[419098.614469] BUG: unable to handle kernel paging request at ffff9001801ff000
[419098.698703] IP: [<ffffffff8102f7a9>] pcache_handle_fault+0x69/0x6c0
[419098.774621] PGD 0
[419098.799579] Oops: 0000 [#1] SMP PROCESSOR
[419098.848457] CPU: 5 PID: 32 Comm: python 4.0.0-lego-ys+ #312
[419098.916054] RIP: 0010:[<ffffffff8102f7a9>]  [<ffffffff8102f7a9>] pcache_handle_fault+0x69/0x6c0
[419099.021089] RSP: 0000:ffff88107e857ed8  EFLAGS: 00010286
[419099.085567] RAX: ffff9001801ff000 RBX: ffff9001801ff000 RCX: 00003ffffffff000
[419099.171884] RDX: 00000801801ff000 RSI: 0000000000601008 RDI: ffff88107e83d648
[419099.258199] RBP: ffff88107e857f18 R08: 00007ffff7fe3000 R09: 00007ffff7fe3000
[419099.344516] R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000601008
[419099.430832] R13: ffff88107e83d648 R14: 0000000000000050 R15: 00007ffff7ffe150
[419099.517149] FS:  00007ffff7fdf740(0000) GS:ffff88207fc40000(0000) knlGS:0000000000000000
[419099.614905] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[419099.684582] CR2: ffff9001801ff000 CR3: 000000207fccf000 CR4: 00000000000406a0
[419099.770899] Stack:
[419099.795858] 00007ffff7d8c000 0000000000002000 0000000000000001 0000000000000004
[419099.884254] 0000000000601008 ffff88107e857f58 0000000000000000 00007ffff7ffe150
[419099.972650] ffff88107e857f48 ffffffff81010082 0000000000000000 0000000000000001
[419100.061047] 000392c29c720ba2 0000000000000000 00007fffffffdc40 ffffffff8100d91f
[419100.149442] 00007ffff7ffe150 0000000000000000 000392c29c720ba2 0000000000000001
[419100.237839] Call Trace:
[419100.267998] <TSK>
[419100.291917] [<ffffffff81010082>] do_page_fault+0xa2/0x1a0
[419100.357434] [<ffffffff8100d91f>] page_fault+0x1f/0x30
[419100.418792] <EOT>


M:
...
[419142.163396] handle_p2m_pcache_miss() cpu 4 I nid:0 pid:32 tgid:32 flags:50 vaddr:0x7ffff7a4c010
[419142.268460] handle_p2m_pcache_miss() cpu 4 O nid:0 pid:32 tgid:32 flags:50 vaddr:0x7ffff7a4c010
(Last Message)
```

Dig deeper:
```c hl_lines="4 5"
int pcache_handle_fault(struct mm_struct *mm,
                        unsigned long address, unsigned long flags)
{
        ..
        pgd = pgd_offset(mm, address);
        pr_info("    addr: %#lx, pgd: %p\n", address, pgd);
        pud = pud_alloc(mm, pgd, address);
        pr_info("    addr: %#lx, pgd: %p pud %p\n", address, pgd, pud);
        if (!pud)
                return VM_FAULT_OOM;
        pmd = pmd_alloc(mm, pud, address);
        if (!pmd)
..
}

[21130.503314] strace__mprotect cpu5 start=0x7ffff7d8c000, len=0x2000, prot(0x1)=PROT_READ
[21130.598994] SYSC_mprotect() cpu(5) tsk(32/32/python) user-ip:0x7ffff7df3d27
[21130.682193]     start:0x7ffff7d8c000,len:0x2000,prot:0x1
[21130.745635]     addr: 0x601008, pgd: ffff88207fccf000
[21130.805954]     addr: 0x601008, pgd: ffff88207fccf000 pud ffff9001801ff000
[21130.888116] BUG: unable to handle kernel paging request at ffff9001801ff000
[21130.971314] IP: [<ffffffff8102fa11>] pcache_handle_fault+0x91/0x6f0
```

Print pgd and pud info, these three messages are related and the last one leads to panic:
```c hl_lines="4 8 12"
wuklab13 ~/ys/0308-6
[  479.375498] addr: 0x400040, pgd: ffff88207fccf000
[  479.435819] pud_alloc_one(): addr: 0x400040, pud: ffff88207fc6f000
[  479.511739] pud_alloc(): addr: 0x400040 pgd ffff88207fccf000, pgd.cont_va ffff88207fc6f000, pud_index=0x0 pud: ffff88207fc6f000
[  479.649021] addr: 0x400040, pgd: ffff88207fccf000 pud ffff88207fc6f000

[  480.016381] addr: 0x600dd8, pgd: ffff88207fccf000
[  480.076701] pud_alloc(): addr: 0x600dd8 pgd ffff88207fccf000, pgd.cont_va ffff88207fc6f000, pud_index=0x0 pud: ffff88207fc6f000
[  480.213982] addr: 0x600dd8, pgd: ffff88207fccf000 pud ffff88207fc6f000

[  680.072819] addr: 0x601008, pgd: ffff88207fccf000
[  680.133138] pud_alloc(): addr: 0x601008 pgd ffff88207fccf000, pgd.cont_va ffff90107e834000, pud_index=0x0 pud: ffff90107e834000
[  680.270422] addr: 0x601008, pgd: ffff88207fccf000 pud ffff90107e834000

[  680.352583] BUG: unable to handle kernel paging request at ffff90107e834000
[  680.435783] IP: [<ffffffff8102fc43>] pcache_handle_fault+0xb3/0x770
[  680.510664] PGD 0

```

I need to check what happens between 480s to 680s. Something in between corrupted pgtable. I doubt it can be:

- copy_to_user related syscalls
- pcache establish mapping, mempcy
- all other memcpy strcpy etc stuff

---
## 03/02 Fri

TODO:

- {---add vsyscall---}
- {---pcache_exit_process: free rmap, free cacheline, etc. When rmap is NULL, we clearly should free this pcache.---}
- pcache_exit_thread? I don't think we need this. All pcache related activities should relate to mm, or thread group leader, not one particular thread.
- check python bug
- use omnigraffle to draw the whole workflow of pcache.

Phoenix, word_count-seq, 4G dataset, 4GB pcache:
```
[  273.268853] Processor: Processor manager is running.
[  573.272479] page:ffffea0071bb9660 count:0 mapcount:-128
[  573.332903] flags: 0x200000000000300(slab|slob_free)
[  573.392182] page dumped because: VM_BUG_ON_PAGE(page_ref_count(page) == 0)
[  573.474340] ------------[ cut here ]------------
[  573.529459] BUG: failure at ./include/lego/mm.h:251/put_page_testzero()!
[  573.609537] Kernel Panic - not syncing: BUG!
[  573.660496] CPU: 4 PID: 13 Comm: kvictim_flushd 4.0.0-lego+ #18
[  573.731212] Stack:
[  573.755132] ffff88207e4bfe10 ffffffff81023644 0000000000000008 ffff88207e4bfe20
[  573.842490] ffff88207e4bfdd8 0000000021475542 0000000000000000 0000000000000000
[  573.929848] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  574.017205] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  574.104563] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
[  574.191921] Call Trace:
[  574.221039] <TSK>
[  574.243919] [<ffffffff81023650>] panic+0xc2/0xeb
[  574.299038] [<ffffffff8105a35a>] ? client_internal_poll_sendcq+0x2a/0x80
[  574.379115] [<ffffffff8105a4fd>] ? client_send_message_with_rdma_write_with_imm_request+0x14d/0x360
[  574.487273] [<ffffffff8101ac3c>] ? task_tick_rt+0x2c/0xd0
[  574.551751] [<ffffffff81018395>] ? scheduler_tick+0x55/0x60
[  574.618308] [<ffffffff81015a45>] ? tick_handle_periodic+0x45/0x70
[  574.691107] [<ffffffff810064c4>] ? apic_timer_interrupt+0x54/0x90
[  574.763905] [<ffffffff8100dbaa>] ? smp__apic_timer_interrupt+0x6a/0x70
[  574.841903] [<ffffffff8101198d>] ? printk+0x11d/0x1b0
[  574.902222] [<ffffffff81025c00>] __free_pages+0x2e0/0x3c0
[  574.966699] [<ffffffff81028472>] kfree+0x62/0x480
[  575.022858] [<ffffffff8102e6be>] victim_flush_func+0x15e/0x1e0
[  575.092536] [<ffffffff8102e560>] ? victim_try_fill_pcache+0x390/0x390
[  575.169494] [<ffffffff8101e446>] kthread+0xf6/0x120
[  575.227733] [<ffffffff8101e350>] ? __kthread_parkme+0x70/0x70
[  575.296371] [<ffffffff8100de32>] ret_from_fork+0x22/0x30
[  575.359810] <EOT>
```

---
## 03/01 Thur

Weird.
```
[43181.388400] p2m_fork(cpu5): I cur:24-word_count-seq new:25
[43181.435341] p2m_fork(cpu5): O succeed cur:24-word_count-seq new:25
[43181.436013] __pcache_do_fill_page(): I pid:24 tgid:24 address:0x4158d0 flags:0x150
[43181.439246] __pcache_do_fill_page(): O pid:24 tgid:24 address:0x4158d0 flags:0x150 ret:0(OKAY) csum:0x9e8f028e

[43181.510534] __pcache_do_fill_page(): I pid:25 tgid:25 address:0x415000 flags:0x150
[43181.517729] __pcache_do_fill_page(): O pid:25 tgid:25 address:0x415000 flags:0x150 ret:0(OKAY) csum:0xffff88029e8f028e
```

After all, it is TLB issue. I forgot to flush tlb after making the original pte read-only during fork. So the parent will be also to continue RW some pages, which should be process-private.

Lego's current TLB flush is very native, we do tlbflush after each pte changes. This will have worse performance compared to linux's batch flush.

Today's case is flush tlb after making pte read-only. And this really has to be performed one by one
